- README.md
- transcribe_audio.py
* Updated Sound Capture settings accept number input.
* Added Error log saving to file.
> Updated Sound Capture settings accept number input.

- .gitignore
- README.md
- requirements.txt
- setup.bash
- setup.bat
- transcribe_audio.py
This PR adds Linux support for RTT.
It also includes some small cleanups, like:
- Moved base deps to `requirements.txt`
- Added missing dep `colorama`
- Added some checks for `portaudio` for Linux setup
- Extend .gitignore for Python
> Add Linux support

- transcribe_audio.py
- transcribe_audio.spec
* Added better support for lower vram/ram users
* Contributor section was fixed an error with GH desktop pushed cached code rather new code. (Don't know how it  even happened.
> Better support for low ram users.

- transcribe_audio.py
* Added extra ram checks
* Fixed some minor errors
* Added mic table
> Ram Check & Mic Table

- README.md
- transcribe_audio.py
* Fixed an issue where ram would be miss identified after calculations.
* Added an argument to enable fine tuning.
* Fine tuning off by default.
> Added Finetune option & Fixed issue with (V)RAM setting.

- .github/FUNDING.yml
- README.md
- transcribe_audio.py
Bring Forward changes from master to dev.
> Forward Changes

- .gitignore
- transcribe_audio.py
* Added an option to ask for cuda device if multiple GPU are detected.
* Changed Record time out to default 1 second.
* Remove code comments for now, will do better documentation.
* Detect when last updated fixed
* Changed how timezone was handled
* Will check for updates
> Script Changes

- requirements.txt
- transcribe_audio.py
* Changed Updater
* Updated requirements txt
> Updater Changed

- README.md
- setup.bash
- transcribe_audio.py
> Read Me/Setup Update

- README.md
- transcribe_audio.py
Push Changes from Master to Dev
> Master -> Dev

- .gitignore
- requirements_static.txt
- setup.bat
- transcribe_audio.py
* Fixed issue with set up
* Changed the requirements file
> Minor Setup Fix

- transcribe_audio.py
> Point GitHubRepo to right Repo

- README.md
- html_data/index.html
- modules/version_checker.py
- transcribe_audio.py
Update branch # 5 with Master build.
> Master -> #5

- setup.bat
Fix issue where if statement would be ignorred and reinstallation would not happen.
I don't know if reinstalling in setup.bash works as intended, I don't have an environment to test it.
> Reinstallation fix for setup.bat

- setup.bat
* Update setup.bat Fix issue where if statement would be ignored and reinstallation would not happen.
Brings changes from Master -> Dev
> Reinstallation fix for setup.bat (#59) (Bring from Master -> Dev)

- README.md
> Update README.md - correct typo

- blacklist.txt
- html_data/player.html
- modules/stream_transcription_module.py
- remote_microphone.py
- requirements.txt
**Improvements:**
- **Enhanced Error Handling and Retries in Downloading Segments:** - Improved the `download_segment` function in `stream_transcription_module.py` to include more robust error handling and retries for downloading segments. - Added a `max_retries` parameter to the `download_segment` function to specify the number of retry attempts. - The function now handles `requests.exceptions.RequestException` specifically for network-related errors, providing more informative error messages. - Implemented a retry mechanism with an optional `retry_delay` to handle temporary network issues. - Added error handling for `http.client.IncompleteRead` exceptions, which can occur if the connection drops during download.
- **Improved M3U8 Playlist Loading:** - The `load_m3u8_with_retry` function …
> [update] Remote Microphone update and Stream Module Update

- set_up_env.py
- setup.bash
* Env Script precheck added, windows only [for now]
* Bash Script updated
> [update] Scripts Update

- README.md
> PR Master to Upstream

- README.md
> Sponsorship Info

- html_data/index.html
- html_data/static/index.js
- html_data/static/styles.css
- modules/version_checker.py
This update introduces a revision  to the web interface, providing powerful new customization options for the greenscreen overlay.
The web interface (`index.html`) now includes a comprehensive customization panel, designed for users who use the page as a real-time subtitle overlay in streaming software.
-   **Activation:** The panel can be toggled by pressing the `H` key. A temporary toast message appears on page load to inform users of this new feature.
-   **Live Styling Controls:** The panel allows for real-time adjustments to the visual appearance of the overlay. Users can modify:
-   **Greenscreen Background:** Change the background color using a color picker or by entering a color name/hex code.
-   **Font Customization:** Select a font family from a predefined list or enter a …
> Synthalingua Changelog - Version 1.2.3
